### ISSUE TITLE
week1/memo  서버

### ISSUE THREAD

**Issue by cookie-meringue** [Dh3356/likelion_spring_study#1]
## Description
memo server 구현

## Detail
프로젝트 생성
DB 연결 없는 memo 서버 구현
controller, service 사용하기

## Todo
- [x] memo 객체 구현
- [x] memo repository 구현
- [x] DTO 구현
- [x] memo service 구현
- [x] memo controller 구현
- [x] 테스트

## Additional context

**Comment by cookie-meringue** [comment]
controller, service에 대한 단순 사용 학습이므로 DB 연결, DTO, Repository 등 세부적인 부분은 고려하지 않음
