### ISSUE TITLE
week2/DB 연동

### ISSUE THREAD

**Issue by cookie-meringue** [Dh3356/likelion_spring_study#3]
## Description
memo server 에 DB 연동

## Detail
- MYSQL DB 연동
- USER를 구분하는 MEMO 서비스 만들기
- Memo, User 기능 만들기

## Todo
- [x] memo 구현
- [x] DTO 구현
- [x] memo service 구현
- [x] memo controller 구현
- [x] user 구현
- [x] DTO 구현
- [x] user service 구현
- [x] user controller 구현
- [x] 테스트

## Additional context
